name: Guardian
version: 1.5.0
api: 5.0.0
main: veroxcode\Guardian\Guardian
author: VeroxCode

commands:
  guardian:
    description: Guardian Commands
    permission: guardian.admin
    usage: /<guardian> help

permissions:
  guardian.admin:
    description: Admin Permissions
    default: op
  guardian.notify:
    description: Notify everyone if a Player fails a Check
    default: op